name: Publish Docker image

on:
    push:
        branches: ["main"]

jobs:
    push_to_registry:
        name: Push image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Login into Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ss02/dockit:latest
      